### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by lordmen99** [YJ83Lee/facebook_graph_search#1]
this script working for facebook search?

**Comment by YJ83Lee** [comment]
I’m not sure. I just closed my elastic beanstalk instance and didn’t test it recently.

**Comment by lordmen99** [comment]
ok. cause now facebook graph api still pending right?

**Comment by YJ83Lee** [comment]
You will need to provide your own Facebook access token...etc and store them in json format int /home/ec2-user/private_data (I was using the default elastic beanstalk PHP environment)
I did not publish my token in this repository..

I will close this issue for now. Please let me know if you need any other information.
